### ISSUE TITLE
Seems pretty random

### ISSUE THREAD

**Issue by rouen-sk** [davidstutz/password-score#4]
So, first random thing I tried: 
aaaedf65seag6351e - result: very strong
add one more number (aaaedf65seag6351e3) - result: weak
seems legit :)

**Comment by davidstutz** [comment]
You can try to turn off the leetspeak part or the keyboard part ("e" is connected to the "3" on the keyboard). These modules cause the score to be very non-monotonic (i.e., longer password can reduce the score significantly). But this would be the same based on english words: "carpenter" can get a lower score (because it is more common and a correct english word) than "carpent" (which is incorrect, but shorter).
